import Head from "next/head";
import Shell from "@/components/shell";
import Splash from "@/components/splash";
import { Stack } from "@mantine/core";
import Updates from "@/components/updates";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Shell>
          <Stack gap={100}>
            <Splash mt={40} />
            <Updates />
          </Stack>
        </Shell>
      </main>
    </>
  );
}
