import Head from "next/head";
import { Text } from "@mantine/core";
import Shell from "@/components/shell";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Shell>
          <Text ta="center">Hello, world</Text>
        </Shell>
      </main>
    </>
  );
}
